sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fLpM0JU0cqpS4nlPCdBDps9kD+dfztNp8sm+t2Eyq5IrlY2d9o/+YVlcUDGcKPbN8RAk9JKyYz/oiRz6+9Nmj+sxTNsVNvqfLbuuNAQqnHy1QgIfDF/844FnC2Eee8bYxS35NBB1qbherhkF7g4e7h7Pm0Qfb9c2uLic5LhPm/OdP9QjPn3Ej0XeEZm2St1Nm2OY8OzVN75idW81tO5La5q6zM0TgXHJJGFccwONUVuKSNlbb4UxhoiWO7qw8H2dX/LAfpUM62ZnKOozv9luOJicnSnnZ75Av3NhxupZ5d5JzR5JJrM0iUvT4xO4g0oNN1kasa7R1IY6+dIWSCgtzTeiezHHbrC6JQXHycI2MHS5H+X8qFBLB5IwVTu0qtAJvq2Sz/1CI6EfJFdcezcx/WfcKQFR9FTlZy1WOalK0QoC/0d04Igi3tT5TIUkBRbcB+AO66lL6z/x5sgMcshA8L++6FPTPxMF5W7wZTUfSqq2+MvzpI+XnMNnjA34qZn73beEUV76/ncbB3ZSnbl7r/hwfB4IwDLkY8zE11qcnkuNXL86j3ApeD6Pe2O4ToNq+Ycg36oLvCZEWTRUee7qdgUpD8j5CvB3WmlJ5MChzhPs7Eh+I+xMRdJwk1WrB8/MVQQSMS9Vday/bsTcKxwSnxVl9l/uyp62RPtiJ1vfhq8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Penelope-s-English-Experiences--13-Being-Extracts-from-the-Commonplace-Book-of-Penelope-Hamilt__1278
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy